#__author__ = 'jason_lee'
from django.conf.urls import *
from views import *
from order.log_views import *
urlpatterns=patterns('',
            url(r'^home/$',home,name='home'),
            url(r'^permission/deny/$',permission_deny,name='permission_deny'),
	    url(r'^login/$',mylogin,name='login'),
	    url(r'^logout/$',mylogout,name='logout'),
        url(r'^role/info/$',role_info,name='role_info'),
        url(r'^user/info/$',user_info,name='user_info'),
        url(r'^user/add/$',user_add,name='user_add'),
        url(r'^user/edit/$',user_edit,name="user_edit"),
        url(r'^user/remove/$',user_remove,name="user_remove"),
        url(r'^rolename/add/$',role_name_add,name="role_name_add"),
        url(r'^rolename/edit/(?P<role_id>\d+)/$',role_name_edit,name="role_name_edit"),
        url(r'^rolename/remove/$',role_name_remove,name="role_name_remove"),
        #url(r'^(?P<username>\w+)/permission/edit/$',user_permission_edit,name="user_permission_edit"),
        url(r'^(?P<username>\w+)/group/edit/$',user_group_edit,name="user_group_edit"),
	    #url(r'^changepassword/(?P<username>\w+)/$',changepassword,name='changepassword'),
        url(r'^get/permissions/$',get_all_permissions,name="get_permissions"),
        url(r'^get/goal/info/$',server_goals_info,name="get_goal_info"),
        url(r'^get/goal/info/add/$',server_goals_info_add,name="goal_info_add"),
        url(r'^get/goal/info/edit/$',server_goals_info_edit,name="goal_info_edit"),
        url(r'^get/goal/info/remove/$',server_goals_info_remove,name="goal_info_remove"),
        url(r'^server/cut/info/$',server_cut_info,name="get_server_cut_info"),
        url(r'^server/cut/info/add/$',server_cut_info_add,name="get_server_cut_add"),
        url(r'^server/cut/info/edit/$',server_cut_info_edit,name="get_server_cut_edit"),
        url(r'^server/cut/info/remove/$',server_cut_info_remove,name="get_server_cut_remove"),
        url(r'^issuing_person/cut/info/$',issuing_person_cut_info,name="get_issuing_person_cut_info"),
        url(r'^issuing_person/cut/info/add/$',issuing_person_cut_info_add,name="get_issuing_person_cut_add"),
        url(r'^issuing_person/cut/info/edit/$',issuing_person_cut_info_edit,name="get_issuing_person_cut_edit"),
        url(r'^issuing_person/cut/info/remove/$',issuing_person_cut_info_remove,name="get_issuing_person_cut_remove"),
        url(r'^user/log/info/$',user_log_info,name="user_log_info"),
        url(r'^get/object/info/$',get_object_info,name="get_object_info"),

)